/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

@SuppressWarnings("nls")
public final class TDictt extends Token
{
    public TDictt()
    {
        super.setText("dict");
    }

    public TDictt(int line, int pos)
    {
        super.setText("dict");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDictt(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDictt(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDictt text.");
    }
}
