/* This file was generated by SableCC (http://www.sablecc.org/). */

package minipython.node;

import minipython.analysis.*;

@SuppressWarnings("nls")
public final class TDmult extends Token
{
    public TDmult()
    {
        super.setText("**");
    }

    public TDmult(int line, int pos)
    {
        super.setText("**");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDmult(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDmult(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDmult text.");
    }
}
